<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ankit-aw-java" name="Command line test" tests="3" failures="1" timestamp="8 Jun 2016 09:17:35 GMT" time="2.983" errors="0">
  <testcase name="addPositivenumbers" time="0.114" classname="com.allure.test.AddTest"/>
  <testcase name="multiplyTwoNumbers" time="0.001" classname="com.allure.test.AddTest">
    <failure type="junit.framework.AssertionFailedError" message="multiplication result is wrong expected:&amp;lt;10&amp;gt; but was:&amp;lt;5&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: multiplication result is wrong expected:<10> but was:<5>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at com.allure.test.AddTest.multiplyTwoNumbers(AddTest.java:20)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:189)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:105)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:117)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- multiplyTwoNumbers -->
  <testcase name="loginTest" time="2.426" classname="com.allure.test.LoginTest"/>
</testsuite> <!-- Command line test -->
