<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="2983" started-at="2016-06-08T09:17:31Z" finished-at="2016-06-08T09:17:34Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="2983" started-at="2016-06-08T09:17:31Z" finished-at="2016-06-08T09:17:34Z">
      <class name="com.allure.test.AddTest">
        <test-method status="PASS" signature="addPositivenumbers()[pri:0, instance:com.allure.test.AddTest@58038583]" name="addPositivenumbers" duration-ms="114" started-at="2016-06-08T14:47:32Z" finished-at="2016-06-08T14:47:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPositivenumbers -->
        <test-method status="FAIL" signature="multiplyTwoNumbers()[pri:0, instance:com.allure.test.AddTest@58038583]" name="multiplyTwoNumbers" duration-ms="1" started-at="2016-06-08T14:47:32Z" finished-at="2016-06-08T14:47:32Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[multiplication result is wrong expected:<10> but was:<5>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: multiplication result is wrong expected:<10> but was:<5>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at com.allure.test.AddTest.multiplyTwoNumbers(AddTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:189)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:105)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiplyTwoNumbers -->
      </class> <!-- com.allure.test.AddTest -->
      <class name="com.allure.test.LoginTest">
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.allure.test.LoginTest@53dd29e0]" name="loginTest" duration-ms="2426" started-at="2016-06-08T14:47:32Z" finished-at="2016-06-08T14:47:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="kill()[pri:0, instance:com.allure.test.LoginTest@53dd29e0]" name="kill" is-config="true" duration-ms="75" started-at="2016-06-08T14:47:34Z" finished-at="2016-06-08T14:47:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kill -->
      </class> <!-- com.allure.test.LoginTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
